#!/usr/bin/env python3

import os

i = 1
while True:
    f = f'{i}.c'
    if not os.path.exists(f):
        break

    print(f'testing {f}')
    if os.system(f'./scanner {f} 2>&1 | diff {i}.out -') != 0:
        print(f'failed test on {f}')

    i += 1
